name: Build YuiChyanBot App
env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: runYuiChyan.py
          mode: app
          show-memory: yes
          show-progress: yes
          include-package-data: package_name:HELP.*
          include-data-dir: ./yuiChyan/util/textfilter/sensitive_words.txt=yuiChyan/util/textfilter/sensitive_words.txt,./yuiChyan/core/manager/help_res=yuiChyan/core/manager/help_res

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: build/*.exe
          if-no-files-found: error